Comparing the tables

In [1]:
import pyspark
import pandas as pd
import numpy as np


from pyspark.sql import SparkSession
from pyspark.sql.functions import countDistinct
spark = SparkSession.builder.appName('practice').getOrCreate()

WARNING: Using incubator modules: jdk.incubator.vector
Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
25/07/20 23:21:17 WARN Utils: Your hostname, Janna-MBP.local, resolves to a loopback address: 127.0.0.1; using 10.0.0.26 instead (on interface en0)
25/07/20 23:21:17 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
25/07/20 23:21:17 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

In [2]:
df_pd = pd.read_csv("week2-ds.tsv", sep = '\t')
df_pd.head()

,Polygon ID,Hashed Device ID,Unix Timestamp of Visit,Data Source,Date,Time of Day,Day of Week,Time Zone
0,"Blue Nile Blue Nile Jewelry - Fashion Square, ...",9f0bc33ace6a4d2bdd678ae1a64f822646e5fadf,1643151728,X,1/25/22,16:02:08,Tue,America/Phoenix
1,"Blue Nile Blue Nile Jewelry - Fashion Square, ...",ca58bf6ffe8a0cef2d91d39d24eb030228cb4ab1,1643131230,X,1/25/22,10:20:30,Tue,America/Phoenix
2,"Blue Nile Blue Nile Jewelry - Fashion Square, ...",0c275358edf2e911bbfcfab93305f487aa42121f,1643153377,X,1/25/22,16:29:37,Tue,America/Phoenix
3,"Blue Nile Blue Nile Jewelry - Fashion Square, ...",30a03daca53ba0f547196a63e3964dd0fde3d66d,1643142816,X,1/25/22,13:33:36,Tue,America/Phoenix
4,"Blue Nile Blue Nile Jewelry - Fashion Square, ...",b7c057bbd95d16c97b84ac52fb3b8c9691e78f99,1643125135,X,1/25/22,8:38:55,Tue,America/Phoenix

In [3]:
df_ps = spark.read.option('header', 'true').csv('week2-ds.tsv', sep = '\t')
df_ps.show(5)

+--------------------+--------------------+-----------------------+-----------+-------+-----------+-----------+---------------+
|          Polygon ID|    Hashed Device ID|Unix Timestamp of Visit|Data Source|   Date|Time of Day|Day of Week|      Time Zone|
+--------------------+--------------------+-----------------------+-----------+-------+-----------+-----------+---------------+
|Blue Nile Blue Ni...|9f0bc33ace6a4d2bd...|             1643151728|          X|1/25/22|   16:02:08|        Tue|America/Phoenix|
|Blue Nile Blue Ni...|ca58bf6ffe8a0cef2...|             1643131230|          X|1/25/22|   10:20:30|        Tue|America/Phoenix|
|Blue Nile Blue Ni...|0c275358edf2e911b...|             1643153377|          X|1/25/22|   16:29:37|        Tue|America/Phoenix|
|Blue Nile Blue Ni...|30a03daca53ba0f54...|             1643142816|          X|1/25/22|   13:33:36|        Tue|America/Phoenix|
|Blue Nile Blue Ni...|b7c057bbd95d16c97...|             1643125135|          X|1/25/22|    8:38:55|        Tue|America/Phoenix|
+--------------------+--------------------+-----------------------+-----------+-------+-----------+-----------+---------------+
only showing top 5 rows

In [4]:
df1_pd = df_pd.groupby('Date')['Hashed Device ID'].nunique().reset_index(name='Hashed Device ID')
df1_pd

        Date  Hashed Device ID
0     1/1/22                78
1    1/10/22                41
2    1/11/22                44
3    1/12/22                44
4    1/13/22                47
..       ...               ...
177   6/5/22                35
178   6/6/22                39
179   6/7/22                32
180   6/8/22                27
181   6/9/22                24

[182 rows x 2 columns]

In [5]:
df1_ps = df_ps.groupBy('Date').agg(countDistinct('Hashed Device ID')).orderBy("Date")
df1_ps.show()

+-------+--------------------------------+
|   Date|count(DISTINCT Hashed Device ID)|
+-------+--------------------------------+
| 1/1/22|                              78|
|1/10/22|                              41|
|1/11/22|                              44|
|1/12/22|                              44|
|1/13/22|                              47|
|1/14/22|                              64|
|1/15/22|                             121|
|1/16/22|                              62|
|1/17/22|                              71|
|1/18/22|                              35|
|1/19/22|                              31|
| 1/2/22|                              61|
|1/20/22|                              42|
|1/21/22|                              48|
|1/22/22|                              99|
|1/23/22|                              54|
|1/24/22|                              31|
|1/25/22|                              29|
|1/26/22|                              39|
|1/27/22|                              36|
+-------+--------------------------------+
only showing top 20 rows

In [6]:
df1_ps_pd = df1_ps.toPandas()

comparison_result = np.array_equal(df1_pd.values, df1_ps_pd.values)

print(f"The data frames are equal: {comparison_result}")

The data frames are equal: True

In [7]:
df2_pd = df_pd.groupby('Polygon ID')['Hashed Device ID'].nunique().reset_index(name='Hashed Device ID')
df2_pd

                                          Polygon ID  Hashed Device ID
0  Blue Nile Blue Nile Jewelry - Domain Northside...               396
1  Blue Nile Blue Nile Jewelry - Fashion Square, ...              2884
2  Blue Nile Blue Nile Jewelry - Garden State Pla...               726
3  Blue Nile Blue Nile Jewelry - Houston Galleria...              1962
4  Blue Nile Blue Nile Jewelry - Roseville Galler...               963
5  Blue Nile The Mall at Rockingham Park, Salem, ...               426
6  Blue Nile Washington Square, Portland, OR|9695391               164

In [8]:
df2_ps = df_ps.groupBy('Polygon ID').agg(countDistinct('Hashed Device ID')).orderBy("Polygon ID")
df2_ps.show(truncate=False)

+-----------------------------------------------------------------------------------------------------------------------------+--------------------------------+
|Polygon ID                                                                                                                   |count(DISTINCT Hashed Device ID)|
+-----------------------------------------------------------------------------------------------------------------------------+--------------------------------+
|Blue Nile Blue Nile Jewelry - Domain Northside, Austin, TX|11050622                                                          |396                             |
|Blue Nile Blue Nile Jewelry - Fashion Square, Scottsdale, AZ|11088822                                                        |2884                            |
|Blue Nile Blue Nile Jewelry - Garden State Plaza, Paramus, NJ|11050629                                                       |726                             |
|Blue Nile Blue Nile Jewelry - Houston Galleria, Houston, TX|11050619                                                         |1962                            |
|Blue Nile Blue Nile Jewelry - Roseville Galleria1151 Galleria Blvd, Suite 120,,Roseville,95678,CA,USA, Roseville, CA|11259307|963                             |
|Blue Nile The Mall at Rockingham Park, Salem, NH|9695393                                                                     |426                             |
|Blue Nile Washington Square, Portland, OR|9695391                                                                            |164                             |
+-----------------------------------------------------------------------------------------------------------------------------+--------------------------------+

In [9]:
df2_ps_pd = df2_ps.toPandas()

comparison_result = np.array_equal(df2_pd.values, df2_ps_pd.values)

print(f"The data frames are equal: {comparison_result}")

The data frames are equal: True

In [10]:
df3_pd = df_pd.groupby(['Polygon ID', 'Date'])['Hashed Device ID'].nunique().reset_index(name='Hashed Device ID')
df3_pd

,Polygon ID,Date,Hashed Device ID
0,Blue Nile Blue Nile Jewelry - Domain Northside...,1/1/22,10
1,Blue Nile Blue Nile Jewelry - Domain Northside...,1/10/22,8
2,Blue Nile Blue Nile Jewelry - Domain Northside...,1/11/22,9
3,Blue Nile Blue Nile Jewelry - Domain Northside...,1/12/22,5
4,Blue Nile Blue Nile Jewelry - Domain Northside...,1/13/22,7
...,...,...,...
1210,"Blue Nile Washington Square, Portland, OR|9695391",6/5/22,2
1211,"Blue Nile Washington Square, Portland, OR|9695391",6/6/22,3
1212,"Blue Nile Washington Square, Portland, OR|9695391",6/7/22,2
1213,"Blue Nile Washington Square, Portland, OR|9695391",6/8/22,1
1214,"Blue Nile Washington Square, Portland, OR|9695391",6/9/22,3

In [11]:
df3_ps = df_ps.groupBy(['Polygon ID', 'Date']).agg(countDistinct('Hashed Device ID')).orderBy("Polygon ID", "Date")
df3_ps.show(truncate=False)

+-------------------------------------------------------------------+-------+--------------------------------+
|Polygon ID                                                         |Date   |count(DISTINCT Hashed Device ID)|
+-------------------------------------------------------------------+-------+--------------------------------+
|Blue Nile Blue Nile Jewelry - Domain Northside, Austin, TX|11050622|1/1/22 |10                              |
|Blue Nile Blue Nile Jewelry - Domain Northside, Austin, TX|11050622|1/10/22|8                               |
|Blue Nile Blue Nile Jewelry - Domain Northside, Austin, TX|11050622|1/11/22|9                               |
|Blue Nile Blue Nile Jewelry - Domain Northside, Austin, TX|11050622|1/12/22|5                               |
|Blue Nile Blue Nile Jewelry - Domain Northside, Austin, TX|11050622|1/13/22|7                               |
|Blue Nile Blue Nile Jewelry - Domain Northside, Austin, TX|11050622|1/14/22|7                               |
|Blue Nile Blue Nile Jewelry - Domain Northside, Austin, TX|11050622|1/15/22|7                               |
|Blue Nile Blue Nile Jewelry - Domain Northside, Austin, TX|11050622|1/16/22|5                               |
|Blue Nile Blue Nile Jewelry - Domain Northside, Austin, TX|11050622|1/17/22|3                               |
|Blue Nile Blue Nile Jewelry - Domain Northside, Austin, TX|11050622|1/18/22|4                               |
|Blue Nile Blue Nile Jewelry - Domain Northside, Austin, TX|11050622|1/19/22|5                               |
|Blue Nile Blue Nile Jewelry - Domain Northside, Austin, TX|11050622|1/2/22 |3                               |
|Blue Nile Blue Nile Jewelry - Domain Northside, Austin, TX|11050622|1/20/22|5                               |
|Blue Nile Blue Nile Jewelry - Domain Northside, Austin, TX|11050622|1/21/22|3                               |
|Blue Nile Blue Nile Jewelry - Domain Northside, Austin, TX|11050622|1/22/22|10                              |
|Blue Nile Blue Nile Jewelry - Domain Northside, Austin, TX|11050622|1/23/22|7                               |
|Blue Nile Blue Nile Jewelry - Domain Northside, Austin, TX|11050622|1/24/22|5                               |
|Blue Nile Blue Nile Jewelry - Domain Northside, Austin, TX|11050622|1/25/22|2                               |
|Blue Nile Blue Nile Jewelry - Domain Northside, Austin, TX|11050622|1/26/22|5                               |
|Blue Nile Blue Nile Jewelry - Domain Northside, Austin, TX|11050622|1/27/22|5                               |
+-------------------------------------------------------------------+-------+--------------------------------+
only showing top 20 rows

In [12]:
df3_ps_pd = df3_ps.toPandas()

comparison_result = np.array_equal(df3_pd.values, df3_ps_pd.values)

print(f"The data frames are equal: {comparison_result}")

The data frames are equal: True

25/07/21 03:32:12 WARN HeartbeatReceiver: Removing executor driver with no recent heartbeats: 441649 ms exceeds timeout 120000 ms
25/07/21 03:32:12 WARN SparkContext: Killing executors is not supported by current scheduler.
25/07/21 03:32:16 WARN Executor: Issue communicating with driver in heartbeater
org.apache.spark.SparkException: Exception thrown in awaitResult:
	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:53)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:342)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:101)
	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:85)
	at org.apache.spark.storage.BlockManagerMaster.registerBlockManager(BlockManagerMaster.scala:81)
	at org.apache.spark.storage.BlockManager.reregister(BlockManager.scala:669)
	at org.apache.spark.executor.Executor.reportHeartBeat(Executor.scala:1296)
	at org.apache.spark.executor.Executor.$anonfun$heartbeater$1(Executor.scala:307)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1937)
	at org.apache.spark.Heartbeater$$anon$1.run(Heartbeater.scala:46)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)
Caused by: org.apache.spark.SparkException: Exception thrown in awaitResult:
	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:53)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:342)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
	at org.apache.spark.util.RpcUtils$.makeDriverRef(RpcUtils.scala:36)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.driverEndpoint$lzycompute(BlockManagerMasterEndpoint.scala:132)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$driverEndpoint(BlockManagerMasterEndpoint.scala:131)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$lzycompute$1(BlockManagerMasterEndpoint.scala:700)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$1(BlockManagerMasterEndpoint.scala:699)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$register(BlockManagerMasterEndpoint.scala:739)
	at org.apache.spark.storage.BlockManagerMasterEndpoint$$anonfun$receiveAndReply$1.applyOrElse(BlockManagerMasterEndpoint.scala:141)
	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:104)
	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:216)
	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:101)
	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:76)
	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:42)
	... 3 more
Caused by: org.apache.spark.rpc.RpcEndpointNotFoundException: Cannot find endpoint: spark://CoarseGrainedScheduler@10.0.0.26:53542
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1(NettyRpcEnv.scala:151)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1$adapted(NettyRpcEnv.scala:147)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:470)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl.execute(ExecutionContextImpl.scala:21)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:429)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:338)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:285)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:504)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl.execute(ExecutionContextImpl.scala:21)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:429)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:338)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:285)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:504)
	at scala.concurrent.ExecutionContext$parasitic$.execute(ExecutionContext.scala:222)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:429)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:335)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:285)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:278)
	at scala.concurrent.Promise.trySuccess(Promise.scala:99)
	at scala.concurrent.Promise.trySuccess$(Promise.scala:99)
	at scala.concurrent.impl.Promise$DefaultPromise.trySuccess(Promise.scala:104)
	at org.apache.spark.rpc.netty.NettyRpcEnv.onSuccess$1(NettyRpcEnv.scala:228)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$askAbortable$5(NettyRpcEnv.scala:242)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$askAbortable$5$adapted(NettyRpcEnv.scala:241)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:484)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl.execute(ExecutionContextImpl.scala:21)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:429)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:338)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:285)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:278)
	at scala.concurrent.Promise.complete(Promise.scala:57)
	at scala.concurrent.Promise.complete$(Promise.scala:56)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:104)
	at scala.concurrent.Promise.success(Promise.scala:91)
	at scala.concurrent.Promise.success$(Promise.scala:91)
	at scala.concurrent.impl.Promise$DefaultPromise.success(Promise.scala:104)
	at org.apache.spark.rpc.netty.LocalNettyRpcCallContext.send(NettyRpcCallContext.scala:50)
	at org.apache.spark.rpc.netty.NettyRpcCallContext.reply(NettyRpcCallContext.scala:32)
	at org.apache.spark.rpc.netty.RpcEndpointVerifier$$anonfun$receiveAndReply$1.applyOrElse(RpcEndpointVerifier.scala:31)
	... 8 more
25/07/21 03:32:16 ERROR Inbox: Ignoring error
org.apache.spark.SparkException: Exception thrown in awaitResult:
	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:53)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:342)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
	at org.apache.spark.util.RpcUtils$.makeDriverRef(RpcUtils.scala:36)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.driverEndpoint$lzycompute(BlockManagerMasterEndpoint.scala:132)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$driverEndpoint(BlockManagerMasterEndpoint.scala:131)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$lzycompute$1(BlockManagerMasterEndpoint.scala:700)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$1(BlockManagerMasterEndpoint.scala:699)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$register(BlockManagerMasterEndpoint.scala:739)
	at org.apache.spark.storage.BlockManagerMasterEndpoint$$anonfun$receiveAndReply$1.applyOrElse(BlockManagerMasterEndpoint.scala:141)
	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:104)
	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:216)
	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:101)
	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:76)
	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:42)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)
Caused by: org.apache.spark.rpc.RpcEndpointNotFoundException: Cannot find endpoint: spark://CoarseGrainedScheduler@10.0.0.26:53542
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1(NettyRpcEnv.scala:151)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1$adapted(NettyRpcEnv.scala:147)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:470)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl.execute(ExecutionContextImpl.scala:21)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:429)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:338)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:285)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:504)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl.execute(ExecutionContextImpl.scala:21)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:429)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:338)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:285)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:504)
	at scala.concurrent.ExecutionContext$parasitic$.execute(ExecutionContext.scala:222)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:429)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:335)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:285)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:278)
	at scala.concurrent.Promise.trySuccess(Promise.scala:99)
	at scala.concurrent.Promise.trySuccess$(Promise.scala:99)
	at scala.concurrent.impl.Promise$DefaultPromise.trySuccess(Promise.scala:104)
	at org.apache.spark.rpc.netty.NettyRpcEnv.onSuccess$1(NettyRpcEnv.scala:228)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$askAbortable$5(NettyRpcEnv.scala:242)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$askAbortable$5$adapted(NettyRpcEnv.scala:241)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:484)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl.execute(ExecutionContextImpl.scala:21)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:429)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:338)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:285)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:278)
	at scala.concurrent.Promise.complete(Promise.scala:57)
	at scala.concurrent.Promise.complete$(Promise.scala:56)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:104)
	at scala.concurrent.Promise.success(Promise.scala:91)
	at scala.concurrent.Promise.success$(Promise.scala:91)
	at scala.concurrent.impl.Promise$DefaultPromise.success(Promise.scala:104)
	at org.apache.spark.rpc.netty.LocalNettyRpcCallContext.send(NettyRpcCallContext.scala:50)
	at org.apache.spark.rpc.netty.NettyRpcCallContext.reply(NettyRpcCallContext.scala:32)
	at org.apache.spark.rpc.netty.RpcEndpointVerifier$$anonfun$receiveAndReply$1.applyOrElse(RpcEndpointVerifier.scala:31)
	... 8 more
25/07/21 03:44:01 ERROR Inbox: Ignoring error
org.apache.spark.SparkException: Exception thrown in awaitResult:
	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:53)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:342)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
	at org.apache.spark.util.RpcUtils$.makeDriverRef(RpcUtils.scala:36)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.driverEndpoint$lzycompute(BlockManagerMasterEndpoint.scala:132)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$driverEndpoint(BlockManagerMasterEndpoint.scala:131)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$lzycompute$1(BlockManagerMasterEndpoint.scala:700)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$1(BlockManagerMasterEndpoint.scala:699)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$register(BlockManagerMasterEndpoint.scala:739)
	at org.apache.spark.storage.BlockManagerMasterEndpoint$$anonfun$receiveAndReply$1.applyOrElse(BlockManagerMasterEndpoint.scala:141)
	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:104)
	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:216)
	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:101)
	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:76)
	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:42)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)
Caused by: org.apache.spark.rpc.RpcEndpointNotFoundException: Cannot find endpoint: spark://CoarseGrainedScheduler@10.0.0.26:53542
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1(NettyRpcEnv.scala:151)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1$adapted(NettyRpcEnv.scala:147)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:470)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl.execute(ExecutionContextImpl.scala:21)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:429)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:338)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:285)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:504)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl.execute(ExecutionContextImpl.scala:21)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:429)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:338)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:285)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:504)
	at scala.concurrent.ExecutionContext$parasitic$.execute(ExecutionContext.scala:222)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:429)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:335)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:285)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:278)
	at scala.concurrent.Promise.trySuccess(Promise.scala:99)
	at scala.concurrent.Promise.trySuccess$(Promise.scala:99)
	at scala.concurrent.impl.Promise$DefaultPromise.trySuccess(Promise.scala:104)
	at org.apache.spark.rpc.netty.NettyRpcEnv.onSuccess$1(NettyRpcEnv.scala:228)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$askAbortable$5(NettyRpcEnv.scala:242)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$askAbortable$5$adapted(NettyRpcEnv.scala:241)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:484)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl.execute(ExecutionContextImpl.scala:21)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:429)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:338)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:285)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:278)
	at scala.concurrent.Promise.complete(Promise.scala:57)
	at scala.concurrent.Promise.complete$(Promise.scala:56)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:104)
	at scala.concurrent.Promise.success(Promise.scala:91)
	at scala.concurrent.Promise.success$(Promise.scala:91)
	at scala.concurrent.impl.Promise$DefaultPromise.success(Promise.scala:104)
	at org.apache.spark.rpc.netty.LocalNettyRpcCallContext.send(NettyRpcCallContext.scala:50)
	at org.apache.spark.rpc.netty.NettyRpcCallContext.reply(NettyRpcCallContext.scala:32)
	at org.apache.spark.rpc.netty.RpcEndpointVerifier$$anonfun$receiveAndReply$1.applyOrElse(RpcEndpointVerifier.scala:31)
	... 8 more
25/07/21 03:44:01 WARN Executor: Issue communicating with driver in heartbeater
org.apache.spark.SparkException: Exception thrown in awaitResult:
	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:53)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:342)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:101)
	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:85)
	at org.apache.spark.storage.BlockManagerMaster.registerBlockManager(BlockManagerMaster.scala:81)
	at org.apache.spark.storage.BlockManager.reregister(BlockManager.scala:669)
	at org.apache.spark.executor.Executor.reportHeartBeat(Executor.scala:1296)
	at org.apache.spark.executor.Executor.$anonfun$heartbeater$1(Executor.scala:307)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1937)
	at org.apache.spark.Heartbeater$$anon$1.run(Heartbeater.scala:46)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)
Caused by: org.apache.spark.SparkException: Exception thrown in awaitResult:
	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:53)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:342)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)