In [1]:
import pandas as pd

1. Show first five rows:

In [2]:
df = pd.read_csv("week2-ds.tsv", sep = '\t')
df.head()

,Polygon ID,Hashed Device ID,Unix Timestamp of Visit,Data Source,Date,Time of Day,Day of Week,Time Zone
0,"Blue Nile Blue Nile Jewelry - Fashion Square, ...",9f0bc33ace6a4d2bdd678ae1a64f822646e5fadf,1643151728,X,1/25/22,16:02:08,Tue,America/Phoenix
1,"Blue Nile Blue Nile Jewelry - Fashion Square, ...",ca58bf6ffe8a0cef2d91d39d24eb030228cb4ab1,1643131230,X,1/25/22,10:20:30,Tue,America/Phoenix
2,"Blue Nile Blue Nile Jewelry - Fashion Square, ...",0c275358edf2e911bbfcfab93305f487aa42121f,1643153377,X,1/25/22,16:29:37,Tue,America/Phoenix
3,"Blue Nile Blue Nile Jewelry - Fashion Square, ...",30a03daca53ba0f547196a63e3964dd0fde3d66d,1643142816,X,1/25/22,13:33:36,Tue,America/Phoenix
4,"Blue Nile Blue Nile Jewelry - Fashion Square, ...",b7c057bbd95d16c97b84ac52fb3b8c9691e78f99,1643125135,X,1/25/22,8:38:55,Tue,America/Phoenix

2. Number of Rows

In [3]:
df.count()

length = len(df)
print(length)

27307

3. Number of Distinct Rows

In [4]:
unique_rows = len(df.drop_duplicates())
print(unique_rows)

26307

4. Number of Distinct 'Hashed Device ID'

In [5]:
unique_hash = len(df['Hashed Device ID'].drop_duplicates())
print(unique_hash)

7518

5. Number of Distinct Columns

In [6]:
unique_id = len(df['Polygon ID'].drop_duplicates())
print(f'Distinct Polygon IDs: {unique_id}')

unique_source = len(df['Data Source'].drop_duplicates())
print(f'Distinct Data Sources: {unique_source}')

unique_date = len(df['Date'].drop_duplicates())
print(f'Distinct Dates: {unique_date}')

Distinct Polygon IDs: 7
Distinct Data Sources: 4
Distinct Dates: 182

6a. Date , Number of distinct Hashed Device IDs

In [7]:
df.groupby('Date')['Hashed Device ID'].nunique().reset_index(name='Hashed Device ID')

        Date  Hashed Device ID
0     1/1/22                78
1    1/10/22                41
2    1/11/22                44
3    1/12/22                44
4    1/13/22                47
..       ...               ...
177   6/5/22                35
178   6/6/22                39
179   6/7/22                32
180   6/8/22                27
181   6/9/22                24

[182 rows x 2 columns]

6b. Polygon ID, Number of Distinct Hashed Device IDs

In [8]:
df.groupby('Polygon ID')['Hashed Device ID'].nunique().reset_index(name='Hashed Device ID')

                                          Polygon ID  Hashed Device ID
0  Blue Nile Blue Nile Jewelry - Domain Northside...               396
1  Blue Nile Blue Nile Jewelry - Fashion Square, ...              2884
2  Blue Nile Blue Nile Jewelry - Garden State Pla...               726
3  Blue Nile Blue Nile Jewelry - Houston Galleria...              1962
4  Blue Nile Blue Nile Jewelry - Roseville Galler...               963
5  Blue Nile The Mall at Rockingham Park, Salem, ...               426
6  Blue Nile Washington Square, Portland, OR|9695391               164

6c. Polygon ID, Date, Number of Distinct Hashed Device IDs

In [9]:
df.groupby(['Polygon ID', 'Date'])['Hashed Device ID'].nunique().reset_index(name='Hashed Device ID')

,Polygon ID,Date,Hashed Device ID
0,Blue Nile Blue Nile Jewelry - Domain Northside...,1/1/22,10
1,Blue Nile Blue Nile Jewelry - Domain Northside...,1/10/22,8
2,Blue Nile Blue Nile Jewelry - Domain Northside...,1/11/22,9
3,Blue Nile Blue Nile Jewelry - Domain Northside...,1/12/22,5
4,Blue Nile Blue Nile Jewelry - Domain Northside...,1/13/22,7
...,...,...,...
1210,"Blue Nile Washington Square, Portland, OR|9695391",6/5/22,2
1211,"Blue Nile Washington Square, Portland, OR|9695391",6/6/22,3
1212,"Blue Nile Washington Square, Portland, OR|9695391",6/7/22,2
1213,"Blue Nile Washington Square, Portland, OR|9695391",6/8/22,1
1214,"Blue Nile Washington Square, Portland, OR|9695391",6/9/22,3

7a. Source X

In [10]:
source_x = df[df['Data Source'] == 'X']
filter = source_x.groupby('Date')['Hashed Device ID'].nunique().reset_index(name='Hashed Device ID')
filter['Data Source'] = 'X'

filter

        Date  Hashed Device ID Data Source
0     1/1/22                70           X
1    1/10/22                35           X
2    1/11/22                35           X
3    1/12/22                39           X
4    1/13/22                41           X
..       ...               ...         ...
160   6/4/22                 2           X
161   6/5/22                 1           X
162   6/6/22                 1           X
163   6/7/22                 1           X
164   6/8/22                 1           X

[165 rows x 3 columns]

In [11]:
filter = source_x.groupby('Polygon ID')['Hashed Device ID'].nunique().reset_index(name='Hashed Device ID')
filter['Data Source'] = 'X'

filter

,Polygon ID,Hashed Device ID,Data Source
0,Blue Nile Blue Nile Jewelry - Domain Northside...,238,X
1,"Blue Nile Blue Nile Jewelry - Fashion Square, ...",2337,X
2,Blue Nile Blue Nile Jewelry - Garden State Pla...,461,X
3,Blue Nile Blue Nile Jewelry - Houston Galleria...,1342,X
4,Blue Nile Blue Nile Jewelry - Roseville Galler...,677,X
5,"Blue Nile The Mall at Rockingham Park, Salem, ...",236,X
6,"Blue Nile Washington Square, Portland, OR|9695391",111,X

In [12]:
filter = source_x.groupby(['Polygon ID', 'Date'])['Hashed Device ID'].nunique().reset_index(name='Hashed Device ID')
filter['Data Source'] = 'X'

filter

,Polygon ID,Date,Hashed Device ID,Data Source
0,Blue Nile Blue Nile Jewelry - Domain Northside...,1/1/22,7,X
1,Blue Nile Blue Nile Jewelry - Domain Northside...,1/10/22,7,X
2,Blue Nile Blue Nile Jewelry - Domain Northside...,1/11/22,5,X
3,Blue Nile Blue Nile Jewelry - Domain Northside...,1/12/22,3,X
4,Blue Nile Blue Nile Jewelry - Domain Northside...,1/13/22,4,X
...,...,...,...,...
814,"Blue Nile Washington Square, Portland, OR|9695391",4/8/22,2,X
815,"Blue Nile Washington Square, Portland, OR|9695391",4/9/22,2,X
816,"Blue Nile Washington Square, Portland, OR|9695391",6/16/22,1,X
817,"Blue Nile Washington Square, Portland, OR|9695391",6/18/22,1,X
818,"Blue Nile Washington Square, Portland, OR|9695391",6/5/22,1,X

7b. Source C

In [13]:
source_c = df[df['Data Source'] == 'C']

filter = source_c.groupby('Date')['Hashed Device ID'].nunique().reset_index(name='Hashed Device ID')
filter['Data Source'] = 'C'

filter

        Date  Hashed Device ID Data Source
0     1/1/22                 7           C
1    1/10/22                 7           C
2    1/11/22                10           C
3    1/12/22                 5           C
4    1/13/22                 4           C
..       ...               ...         ...
176   6/5/22                 8           C
177   6/6/22                13           C
178   6/7/22                16           C
179   6/8/22                13           C
180   6/9/22                 7           C

[181 rows x 3 columns]

In [14]:
filter = source_c.groupby('Polygon ID')['Hashed Device ID'].nunique().reset_index(name='Hashed Device ID')
filter['Data Source'] = 'C'

filter

,Polygon ID,Hashed Device ID,Data Source
0,Blue Nile Blue Nile Jewelry - Domain Northside...,86,C
1,"Blue Nile Blue Nile Jewelry - Fashion Square, ...",101,C
2,Blue Nile Blue Nile Jewelry - Garden State Pla...,125,C
3,Blue Nile Blue Nile Jewelry - Houston Galleria...,334,C
4,Blue Nile Blue Nile Jewelry - Roseville Galler...,127,C
5,"Blue Nile The Mall at Rockingham Park, Salem, ...",65,C
6,"Blue Nile Washington Square, Portland, OR|9695391",27,C

In [15]:
filter = source_c.groupby(['Polygon ID', 'Date'])['Hashed Device ID'].nunique().reset_index(name='Hashed Device ID')
filter['Data Source'] = 'C'

filter

,Polygon ID,Date,Hashed Device ID,Data Source
0,Blue Nile Blue Nile Jewelry - Domain Northside...,1/1/22,3,C
1,Blue Nile Blue Nile Jewelry - Domain Northside...,1/10/22,2,C
2,Blue Nile Blue Nile Jewelry - Domain Northside...,1/11/22,5,C
3,Blue Nile Blue Nile Jewelry - Domain Northside...,1/12/22,2,C
4,Blue Nile Blue Nile Jewelry - Domain Northside...,1/13/22,2,C
...,...,...,...,...
895,"Blue Nile Washington Square, Portland, OR|9695391",6/4/22,1,C
896,"Blue Nile Washington Square, Portland, OR|9695391",6/6/22,2,C
897,"Blue Nile Washington Square, Portland, OR|9695391",6/7/22,1,C
898,"Blue Nile Washington Square, Portland, OR|9695391",6/8/22,1,C
899,"Blue Nile Washington Square, Portland, OR|9695391",6/9/22,2,C

7c. Source Y

In [16]:
source_y = df[df['Data Source'] == 'Y']

filter = source_y.groupby('Date')['Hashed Device ID'].nunique().reset_index(name='Hashed Device ID')
filter['Data Source'] = 'Y'

filter

        Date  Hashed Device ID Data Source
0     1/1/22                 3           Y
1    1/11/22                 7           Y
2    1/12/22                 3           Y
3    1/13/22                 3           Y
4    1/14/22                 3           Y
..       ...               ...         ...
176   6/5/22                 6           Y
177   6/6/22                11           Y
178   6/7/22                17           Y
179   6/8/22                11           Y
180   6/9/22                 9           Y

[181 rows x 3 columns]

In [17]:
filter = source_y.groupby('Polygon ID')['Hashed Device ID'].nunique().reset_index(name='Hashed Device ID')
filter['Data Source'] = 'Y'

filter

,Polygon ID,Hashed Device ID,Data Source
0,Blue Nile Blue Nile Jewelry - Domain Northside...,58,Y
1,"Blue Nile Blue Nile Jewelry - Fashion Square, ...",112,Y
2,Blue Nile Blue Nile Jewelry - Garden State Pla...,76,Y
3,Blue Nile Blue Nile Jewelry - Houston Galleria...,171,Y
4,Blue Nile Blue Nile Jewelry - Roseville Galler...,75,Y
5,"Blue Nile The Mall at Rockingham Park, Salem, ...",40,Y
6,"Blue Nile Washington Square, Portland, OR|9695391",26,Y

In [18]:
filter = source_y.groupby(['Polygon ID', 'Date'])['Hashed Device ID'].nunique().reset_index(name='Hashed Device ID')
filter['Data Source'] = 'Y'

filter

,Polygon ID,Date,Hashed Device ID,Data Source
0,Blue Nile Blue Nile Jewelry - Domain Northside...,1/1/22,1,Y
1,Blue Nile Blue Nile Jewelry - Domain Northside...,1/11/22,5,Y
2,Blue Nile Blue Nile Jewelry - Domain Northside...,1/12/22,2,Y
3,Blue Nile Blue Nile Jewelry - Domain Northside...,1/13/22,2,Y
4,Blue Nile Blue Nile Jewelry - Domain Northside...,1/14/22,2,Y
...,...,...,...,...
838,"Blue Nile Washington Square, Portland, OR|9695391",6/4/22,1,Y
839,"Blue Nile Washington Square, Portland, OR|9695391",6/6/22,2,Y
840,"Blue Nile Washington Square, Portland, OR|9695391",6/7/22,2,Y
841,"Blue Nile Washington Square, Portland, OR|9695391",6/8/22,1,Y
842,"Blue Nile Washington Square, Portland, OR|9695391",6/9/22,2,Y

7d. Source Z

In [19]:
source_z = df[df['Data Source'] == 'Z']

filter = source_z.groupby('Date')['Hashed Device ID'].nunique().reset_index(name='Hashed Device ID')
filter['Data Source'] = 'Z'

filter

        Date  Hashed Device ID Data Source
0    1/11/22                 3           Z
1    1/14/22                 2           Z
2    1/15/22                 1           Z
3    1/19/22                 2           Z
4    1/23/22                 3           Z
..       ...               ...         ...
99    6/5/22                28           Z
100   6/6/22                29           Z
101   6/7/22                17           Z
102   6/8/22                14           Z
103   6/9/22                17           Z

[104 rows x 3 columns]

In [20]:
filter = source_z.groupby('Polygon ID')['Hashed Device ID'].nunique().reset_index(name='Hashed Device ID')
filter['Data Source'] = 'Z'

filter

,Polygon ID,Hashed Device ID,Data Source
0,Blue Nile Blue Nile Jewelry - Domain Northside...,81,Z
1,"Blue Nile Blue Nile Jewelry - Fashion Square, ...",453,Z
2,Blue Nile Blue Nile Jewelry - Garden State Pla...,159,Z
3,Blue Nile Blue Nile Jewelry - Houston Galleria...,325,Z
4,Blue Nile Blue Nile Jewelry - Roseville Galler...,169,Z
5,"Blue Nile The Mall at Rockingham Park, Salem, ...",127,Z
6,"Blue Nile Washington Square, Portland, OR|9695391",28,Z

In [21]:
filter = source_z.groupby(['Polygon ID', 'Date'])['Hashed Device ID'].nunique().reset_index(name='Hashed Device ID')
filter['Data Source'] = 'Z'

filter

,Polygon ID,Date,Hashed Device ID,Data Source
0,Blue Nile Blue Nile Jewelry - Domain Northside...,1/11/22,1,Z
1,Blue Nile Blue Nile Jewelry - Domain Northside...,1/15/22,1,Z
2,Blue Nile Blue Nile Jewelry - Domain Northside...,1/19/22,1,Z
3,Blue Nile Blue Nile Jewelry - Domain Northside...,1/23/22,1,Z
4,Blue Nile Blue Nile Jewelry - Domain Northside...,1/24/22,1,Z
...,...,...,...,...
432,"Blue Nile Washington Square, Portland, OR|9695391",6/30/22,1,Z
433,"Blue Nile Washington Square, Portland, OR|9695391",6/4/22,1,Z
434,"Blue Nile Washington Square, Portland, OR|9695391",6/5/22,1,Z
435,"Blue Nile Washington Square, Portland, OR|9695391",6/6/22,2,Z
436,"Blue Nile Washington Square, Portland, OR|9695391",6/9/22,2,Z